### ISSUE TITLE
[que]

### ISSUE THREAD

**Issue by IvanIsak2000** [mb6ockatf/liprikontelegram#7]
Hi bro, i want to ask you why you learn `Lua` ? You want to make your `roblox` or `wow` analog?

**Comment by mb6ockatf** [comment]
@IvanIsak2000 hi. the thing is, i was stunned of how simple this language is. it very like python, but with all the useless things thrown away.

after 4 years doing python only, i felt i am fed up with it. i needed a change to something else; that's why i started looking for change. i considered **perl**, **lua** and **cobol**. perl because of parsing, i do it a lot when debugging linux. cobol because old and fun. lua - because extremely simple, and modern.

no, i'm not into computer games: never played roblox.

also, check out [nelua](https://nelua.io/) - this language is sometimes even faster, than **c**

**Comment by IvanIsak2000** [comment]
> @IvanIsak2000 hi. the thing is, i was stunned of how simple this language is. it very like python, but with all the useless things thrown away.
> 
> after 4 years doing python only, i felt i am fed up with it. i needed a change to something else; that's why i started looking for change. i considered **perl**, **lua** and **cobol**. perl because of parsing, i do it a lot when debugging linux. cobol because old and fun. lua - because extremely simple, and modern.
> 
> no, i'm not into computer games: never played roblox.
> 
> also, check out [nelua](https://nelua.io/) - this language is sometimes even faster, than **c**

Nice, bro. I see you love exotic languages)

**Comment by mb6ockatf** [comment]
> > @IvanIsak2000 hi. the thing is, i was stunned of how simple this language is. it very like python, but with all the useless things thrown away.
> > after 4 years doing python only, i felt i am fed up with it. i needed a change to something else; that's why i started looking for change. i considered **perl**, **lua** and **cobol**. perl because of parsing, i do it a lot when debugging linux. cobol because old and fun. lua - because extremely simple, and modern.
> > no, i'm not into computer games: never played roblox.
> > also, check out [nelua](https://nelua.io/) - this language is sometimes even faster, than **c**
> 
> Nice, bro. I see you love exotic languages)

@IvanIsak2000 why exotic?

**Comment by IvanIsak2000** [comment]
> > > @IvanIsak2000 hi. the thing is, i was stunned of how simple this language is. it very like python, but with all the useless things thrown away.
> > > after 4 years doing python only, i felt i am fed up with it. i needed a change to something else; that's why i started looking for change. i considered **perl**, **lua** and **cobol**. perl because of parsing, i do it a lot when debugging linux. cobol because old and fun. lua - because extremely simple, and modern.
> > > no, i'm not into computer games: never played roblox.
> > > also, check out [nelua](https://nelua.io/) - this language is sometimes even faster, than **c**
> > 
> > 
> > Nice, bro. I see you love exotic languages)
> 
> @IvanIsak2000 why exotic?

Well because. Have you tried writing in Pascal?)

**Comment by mb6ockatf** [comment]
> > > > @IvanIsak2000 hi. the thing is, i was stunned of how simple this language is. it very like python, but with all the useless things thrown away.
> > > > after 4 years doing python only, i felt i am fed up with it. i needed a change to something else; that's why i started looking for change. i considered **perl**, **lua** and **cobol**. perl because of parsing, i do it a lot when debugging linux. cobol because old and fun. lua - because extremely simple, and modern.
> > > > no, i'm not into computer games: never played roblox.
> > > > also, check out [nelua](https://nelua.io/) - this language is sometimes even faster, than **c**
> > > 
> > > 
> > > Nice, bro. I see you love exotic languages)
> > 
> > 
> > @IvanIsak2000 why exotic?
> 
> Well because. Have you tried writing in Pascal?)

yes, i have. it was awful. nice that in my school we study python instead of that

you may have thought i like old languages. i do not. i mean, i *wanted* to code in cobol, perl and stuff. i wanted to learn **ada** "just because. see, i have never actually written a line of those languages, because they're not required for any job. the most esoteric thing i tried was BF, which was for what it's name stands for and to feel "wow, so many features" when doing asm for the first time.

BF is actually assembly, but you have 8 bits of memory available at the same time instead of 128 in x32 asm (4 registers by 32 bit), commands are `< > . , [ ]` instead of self-explanatory `MOV`, `MUL`, `ADD`, etc, and you mind is being raped, of course. checkout [this](https://github.com/mb6ockatf/silver-potato) genius project ))

**Comment by mb6ockatf** [comment]
@IvanIsak2000 imagine what i felt when writing [this](https://github.com/mb6ockatf/silver-potato/blame/206f6ec2d57042c9eb0190228cf0777b3295ad4a/tables/squares_table.b#L1-L540)

**Comment by IvanIsak2000** [comment]
> @IvanIsak2000 imagine what i felt when writing [this](https://github.com/mb6ockatf/silver-potato/blame/206f6ec2d57042c9eb0190228cf0777b3295ad4a/tables/squares_table.b#L1-L540)

Hm bro, i understand nothing
